apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.scheduler.name }}
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: scheduler-plugins
    app.kubernetes.io/part-of: scheduler-plugins
    {{- include "chart.labels" . | nindent 4 }}
